parameters:
    ezpublish.fieldtype.ezyt.class: EzSystems\YouTubeFieldType\Core\FieldType\Type
    ezpublish.fieldtype.ezyt.converter.class: EzSystems\YouTubeFieldType\Core\FieldType\LegacyConverter
    ezpublish.fieldtype.ezyt.form_mapper.class: EzSystems\YouTubeFieldType\Core\FieldType\FormMapper
services:
    ezpublish.fieldtype.ezyt:
        class: EzSystems\YouTubeFieldType\Core\FieldType\Type
        parent: ezpublish.fieldType
        tags:
            - {name: ezpublish.fieldType, alias: ezyt}
    ezpublish.fieldtype.ezyt.converter.:
        class: EzSystems\YouTubeFieldType\Core\FieldType\LegacyConverter
        tags:
            - {name: ezpublish.storageEngine.legacy.converter, alias: ezyt, lazy: true, callback: '::create'}
    ezpublish.fieldtype.ezyt.form_mapper:
        class: EzSystems\YouTubeFieldType\Core\FieldType\FormMapper
        arguments: [@translator]
        tags:
            - {name: ez.fieldFormMapper.definition, fieldType: ezyt}
    ezpublish.fieldtype.indexable.ezyt:
        class: %ezpublish.fieldtype.indexable.unindexed.class%
        tags:
            - {name: ezpublish.fieldType.indexable, alias: ezyt}